### ISSUE TITLE
Investigate failure to validate snapshot using paritydb and not for rocksdb

### ISSUE THREAD

**Issue by sudo-shashank** [ChainSafe/forest#2472] opened 2023-01-25 15:51 UTC
**Issue summary**
Snapshot validation fails when using paritydb whereas rocksdb is able to validate the same snapshot file.
Steps to reproduce:
1. cargo clean
2. ParityDb: cargo build --release --no-default-features --features forest_fil_cns,paritydb 
RocksDb: cargo build --release 
3. ./target/release/forest --encrypt-keystore false --import-snapshot filecoin_snapshot_mainnet_2023-01-25_height_2544000.car --halt-after-import
4. ./target/release/forest --encrypt-keystore false --import-snapshot filecoin_snapshot_mainnet_2023-01-25_height_2544000.car --halt-after-import --skip-load --height 2543960

ParityDb:
![Screenshot from 2023-01-25 20-20-47](https://user-images.githubusercontent.com/99187193/214609888-5ef34829-0ab0-418e-8d84-bebde5910685.png)

RocksDb:
![Screenshot from 2023-01-25 19-45-16](https://user-images.githubusercontent.com/99187193/214609864-0a22c92e-6b39-4707-851b-d25237a1c6d3.png)

**Other information and links**
Snapshot: [filecoin_snapshot_mainnet_2023-01-25_height_2544000.car](https://pub-fd31751bcb69400eb39e694385c19457.r2.dev/minimal/2544000_2023_01_25T06_00_00Z.car)
Height validated: 40 epochs
Branch: main (https://github.com/ChainSafe/forest/commit/ad126d63b95f5f0f1ca88e32169b6ce7a7f14200)

**Comment by elmattic** [comment] 2023-01-26 11:57
Can you share your OS and OS version? Thanks.

**Comment by elmattic** [comment] 2023-01-27 11:28
Looks like it was (according to DO):

```
forest-shashank
16 GB Memory / 320 GB Disk / BLR1 - Ubuntu 22.10 x64
```

**Comment by elmattic** [comment] 2023-01-30 11:29
Closing as we are both unable to reproduce.

**Closed by elmattic** 2023-01-30 11:29 UTC
