### ISSUE TITLE
error: failed to resolve: use of undeclared type or module `log`,When I use "cargo build the forest project ".

### ISSUE THREAD

**Issue by ttj-admin** [ChainSafe/forest#510] opened 2020-06-20 01:50 UTC
**Describe the bug**
failed to resolve: use of undeclared type or module `log`

**To Reproduce**
1. Go to 'forest'
2. Run 'cargo build --release' in my local develop environment.
3.    Compiling tide v0.9.0
error[E0433]: failed to resolve: use of undeclared type or module `log`
  --> /Users/luozhiwei/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.9.0/src/log/mod.rs:30:5
   |
30 |     crate::log::info!("Logger started", { level: "Info" });
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `log`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

But I had run the command "make install "No error occurred。

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.5
 - Rust version :rustc 1.45.0-nightly (a74d1862d 2020-05-14)
 - Branch/commit

Thank you 🙏

**Comment by austinabell** [comment] 2020-06-20 14:03
Hmm interesting, I can't replicate this issue with the same setup as you, but I did look into the Tide crate and that reference does seem a bit weird, I'll try to open a PR to change or open an issue on their end

**Comment by austinabell** [comment] 2020-06-22 01:52
@ttj-admin try running `cargo update`. Closing for now because it doesn't seem reproducible, but feel free to open back up if the issue persists

**Closed by austinabell** 2020-06-22 01:52 UTC
Labels: Type: Bug
