### ISSUE TITLE
Forest run into unrecoverable error state in evaluating network head

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2718] opened 2023-03-28 04:14 UTC
**Describe the bug**

Forest run into unrecoverable error state in evaluating network head in sync check container
epoch: 2719200 

The error is transient, another forest instance of mine worked fine

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```
2023-03-27T12:49:31.887120Z  INFO forest_chain_sync::chain_muxer: Local node is behind the network, starting BOOTSTRAP from LOCAL_HEAD = 2719200 -> NETWORK_HEAD = 2720499
2023-03-27T12:49:31.887214Z ERROR forest_chain_sync::chain_muxer: Bootstrapping failed, re-evaluating the network head to retry the bootstrap. Error = TipsetRangeSyncer(TipsetRangeWithBadBlock(Cid(bafy2bzacecozeyvky3hqbaf5taswa53yz6blyckcoxinmovqtgjcp4nir7upe), "chain contained bafy2bzaceaobakmfdjtsw7b4twvrvjgvhhix7hwxwpfwpwb2fb5sd7lsil5pk"))
2023-03-27T12:49:31.887224Z  INFO forest_chain_sync::chain_muxer: Evaluating network head...
2023-03-27T12:50:15.793043Z  INFO forest_chain_sync::chain_muxer: Local node is behind the network, starting BOOTSTRAP from LOCAL_HEAD = 2719200 -> NETWORK_HEAD = 2720500
2023-03-27T12:50:15.793220Z ERROR forest_chain_sync::chain_muxer: Bootstrapping failed, re-evaluating the network head to retry the bootstrap. Error = TipsetRangeSyncer(TipsetRangeWithBadBlock(Cid(bafy2bzaceckveinsh2jtlzxtsap2yvywgjoewhuqwy2ximrs3h6jdiq5fncuk), "chain contained bafy2bzacecozeyvky3hqbaf5taswa53yz6blyckcoxinmovqtgjcp4nir7upe"))
2023-03-27T12:50:15.793236Z  INFO forest_chain_sync::chain_muxer: Evaluating network head...
2023-03-27T12:50:37.229879Z  WARN forest_libp2p::hello::behaviour: sending on a closed channel
2023-03-27T12:51:07.749109Z  INFO forest_chain_sync::chain_muxer: Local node is behind the network, starting BOOTSTRAP from LOCAL_HEAD = 2719200 -> NETWORK_HEAD = 2720502
2023-03-27T12:51:07.749238Z ERROR forest_chain_sync::chain_muxer: Bootstrapping failed, re-evaluating the network head to retry the bootstrap. Error = TipsetRangeSyncer(TipsetRangeWithBadBlock(Cid(bafy2bzaced3unnmzvt36fudwj5wsv4a3pu3fq2xxmj7cczc74owc2itwudnpk), "chain contained bafy2bzaceckveinsh2jtlzxtsap2yvywgjoewhuqwy2ximrs3h6jdiq5fncuk"))
2023-03-27T12:51:07.749256Z  INFO forest_chain_sync::chain_muxer: Evaluating network head...
2023-03-27T12:52:02.038027Z  INFO forest_chain_sync::chain_muxer: Local node is behind the network, starting BOOTSTRAP from LOCAL_HEAD = 2719200 -> NETWORK_HEAD = 2720504
2023-03-27T12:52:02.661164Z ERROR forest_chain_sync::chain_muxer: Bootstrapping failed, re-evaluating the network head to retry the bootstrap. Error = TipsetRangeSyncer(TipsetRangeWithBadBlock(Cid(bafy2bzacebvtbpr33i7inncwipcndi472v6dsjzrve6742a3seiwzk2ezgy24), "chain contained bafy2bzaced3unnmzvt36fudwj5wsv4a3pu3fq2xxmj7cczc74owc2itwudnpk"))
2023-03-27T12:52:02.661219Z  INFO forest_chain_sync::chain_muxer: Evaluating network head...
2023-03-27T12:52:03.671081Z  WARN forest_chain_sync::chain_muxer: Validating tipset received through GossipSub failed: Tipset block = [CID = bafy2bzaceclkcrnvgyoc4cbonlivobi3pgr24glq5r4x7gfmvoc42rufsq3ue] is invalid: chain contained bafy2bzacebvtbpr33i7inncwipcndi472v6dsjzrve6742a3seiwzk2ezgy24
  ```
</details>

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**

- OS:
- Rust version(e.g. `rustc --version`)
- Branch/commit

**Other information and links**

**Comment by elmattic** [comment] 2023-03-28 08:09
Looks like some block are marked as bad but this should not be the case:
E.g. [bafy2bzaceckveinsh2jtlzxtsap2yvywgjoewhuqwy2ximrs3h6jdiq5fncuk](https://filfox.info/en/block/bafy2bzaceckveinsh2jtlzxtsap2yvywgjoewhuqwy2ximrs3h6jdiq5fncuk)

**Comment by elmattic** [comment] 2023-03-28 09:48
Trying to reproduce it and saving some snapshot on our DO spaces if I can.

**Comment by LesnyRumcajs** [comment] 2023-03-28 20:45
It happened again, snapshot: `2722320_2023_03_28T04_00_00Z.car`

The first failure was a state mismatch
```
2023-03-28T16:26:52.157329Z  WARN forest_chain_sync::tipset_syncer: Validating block [CID = bafy2bzaceckgtffiaqudpvnghzngm3dqcc4jj6deseyepyedna73oezb5bdgs] in EPOCH = 2723460 failed: Validation error: Validation error: Parent state root did not match computed state: bafy2bzacea7tks57q3aul4nmz7ydrxv6d5ouzg3jlclobgi3s5wqmluaxkx7q (header), bafy2bzacedsxc3p6irloz7fz3bxma43dkab5o5tsm5xjuas4haakwsdyr5u5e (computed)    
```
Full logs [here](https://github.com/ChainSafe/forest/files/11094002/logs.txt)

**Comment by elmattic** [comment] 2023-03-29 08:20
@LesnyRumcajs I tried yesterday with snapshots `2719200_2023_03_27T02_00_00Z.car` and `2720400_2023_03_27T12_00_00Z.car` and was not able to reproduce.

Will try with yours.

**Comment by LesnyRumcajs** [comment] 2023-05-29 08:36
It happened again a few days ago.

[forest-mainnet_2023-05-25T14_56_31_forest](https://github.com/ChainSafe/forest/files/11590067/logs.txt)

**Comment by LesnyRumcajs** [comment] 2023-10-03 14:36
Not reproducible.

**Comment by LesnyRumcajs** [comment] 2024-01-08 13:33
Re-opening. This consistently causes issues in the sync check. It may be that Forest is not crash-resistant. Recent failure 
[forest-mainnet_2024-01-08T12_36_58_forest.txt](https://github.com/ChainSafe/forest/files/13860975/forest-mainnet_2024-01-08T12_36_58_forest.txt)

**Comment by hanabi1224** [comment] 2024-03-06 15:21
This should have been fixed by https://github.com/ChainSafe/forest/pull/4027

**Comment by LesnyRumcajs** [comment] 2024-03-11 08:43
@hanabi1224 I'll close it. We can always revive it if the bug resurfaces.

**Closed** 2024-03-11 08:43 UTC
Labels: Bug
