### ISSUE TITLE
fix `Filecoin.GasEstimateMessageGas`

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4663] opened 2024-08-21 14:38 UTC
As reported in the `curio-dev` channel [here](https://filecoinproject.slack.com/archives/C06GD1SS56Y/p1721634429310969):

> Seems like forest gas estimation is acting up - My Calibnet WindowPoSts failed to send with
```
error: sending proof message: send error: RPC error (-32603): given message has too high of a gas limit
```
> Snap later failed with
```
error: pushing message to mpool: send error: RPC error (-32603): gas_limit 0 cannot be less than cost 4958563.000 of storing a message on chain
```
> (lotus-backed sends failed with `error: pushing message to mpool: GasEstimateMessageGas error: message execution failed: exit ErrIllegalArgument(16), reason: message failed with backtrace: 00: f0116147 (method 35) -- invalid update 0 while requiring activation success: sector isn't active, skipping sector 29 (16) (RetCode=16)` so this one is probably not returning the correct error in Gas Estimation)

Sadly, we have no snapshots of the invalid behaviour.

**Comment by LesnyRumcajs** [comment] 2024-08-22 09:41
Updated the issue - the method is implemented, but something is not working right.

**Comment by LesnyRumcajs** [comment] 2024-09-02 09:00
Blocked by https://github.com/ChainSafe/forest/issues/4716

**Comment by ansermino** [comment] 2024-11-08 05:36
@LesnyRumcajs Please confirm this is unblocked and remove the label if so

**Comment by LesnyRumcajs** [comment] 2024-11-08 06:03
@ansermino It is not unblocked because it is not actionable given we don't have means of reproducing this. We are waiting on Curio devs on this, given it happen only on their side.

**Comment by LesnyRumcajs** [comment] 2024-12-05 11:31
Closing. We can re-open when (if) the issue is confirmed.

**Closed by LesnyRumcajs** 2024-12-05 11:31 UTC
Labels: Type: Bug, Status: BLOCKED
