### ISSUE TITLE
SyncSubmitBlock

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#4245] opened 2024-04-19 13:13 UTC
The block submission to the swarm is done.

The sanity checks are not, as this requires introducing some extra abstractions and infra.

**Comment by alt-ivan** [comment] 2024-05-08 10:17
Hi!

Unfortunately, seems like the chain head still doesn't get updated. I'm not sure why. I've set tracing to `debug` (`info` for the most noise-producing stuff) and I'm attaching a log. Hopefully it's at least a little bit helpful. 

[forestlog.txt](https://github.com/ChainSafe/forest/files/15247188/forestlog.txt)

The commit hash from which Forest was built for testing is `3a1291d4655fb641a85d25dd288cd3f19d5c2c2d` .
The testing was performed on a local 2K devnet, with Forest bootstrapped and synced via a Lotus node.

Tested using custom miner that is tested against Lotus and works on the same devnet on the Lotus node.

**Comment by alt-ivan** [comment] 2024-05-08 13:39
@ruseinov 

Hi Roman,

I don't currently have a great method of reproducing to share. I tried quickly jury-rigging `lotus-miner` to work with Forest as means of being able to create a repro but I haven't had much success yet. 

Here's the RPC sequence used by the custom miner:

1) ChainHead 
2) MinerGetBaseInfo -> Beacon entries & is eligible for mining
3) WalletSign -> VRFProof for computing election proof
4) MinerGetBaseInfo -> Sector info for winning PoST
5) WalletSign -> Signing computed block ticket hash
6) MpoolSelect -> Messages to include in block
7) MinerCreateBlock 
8) SyncSubmitBlock -> With result from MinerCreateBlock
9) ChainHead 

The only change I made is to hard-code `block_delay_secs` from `StateGetNetworkParams` as that RPC isn't implemented in Forest yet. I used the same value returned by the Lotus node.

I have also manually run each of these against both Lotus/Forest synced to the same tipset/head and all RPCs listed here return identical responses on both Forest and Lotus nodes for the same inputs. 

If you would find it helpful, I can share the request/response for each of these as well.

**Comment by ruseinov** [comment] 2024-05-10 10:19
@alt-ivan 
Thanks for lining that up for me, it's helpful. The requests and responses would be nice to see as well if possible.

With the sequence above - how can we be sure that the head is never set?

Bear in mind that the way this works in `forest` is that a block is sent to the message queue for processing, so there are no guarantees as to exactly when it actually gets processed, though it should be quite fast. Have you tried verifying that the given block never makes it into the chain?

**Comment by ruseinov** [comment] 2024-05-10 10:27
> 3a1291d4655fb641a85d25dd288cd3f19d5c2c2d

This does not seem to exist anymore, could you try the latest `main`?  Though as long as it had my latest `SyncSubmitBlock` change - it should not matter.

**Comment by alt-ivan** [comment] 2024-05-10 16:07
@ruseinov 

> The requests and responses would be nice to see as well if possible.

Seems like I didn't save them after all 🤦 ... I'll redo the sequence and send the requests/responses. Sorry for the delay.

> With the sequence above - how can we be sure that the head is never set?

Calling `ChainHead` returns the same tipset as before the `SyncSubmitBlock` call. Also, `SyncSubmitBlock` can be called over and over again with the same block and it will return a successful result, but the blocks seems to get "eaten" somewhere.

> Bear in mind that the way this works in forest is that a block is sent to the message queue for processing, so there are no guarantees as to exactly when it actually gets processed, though it should be quite fast. Have you tried verifying that the given block never makes it into the chain?

I figured as much when looking at the codebase. I only stepped through the `SyncSubmitBlock` impl and there I saw that the created tipset doesn't get a CID assigned to it at that point in time. After that I didn't know where to follow the propagation of the block to see if it gets recorded anywhere using `GetChainBlock`, because I couldn't find its CID if it did.

**Comment by ruseinov** [comment] 2024-05-14 11:03
> I figured as much when looking at the codebase. I only stepped through the `SyncSubmitBlock` impl and there I saw that the created tipset doesn't get a CID assigned to it at that point in time. After that I didn't know where to follow the propagation of the block to see if it gets recorded anywhere using `GetChainBlock`, because I couldn't find its CID if it did.

That is helpful, let me check..

**Comment by ruseinov** [comment] 2024-05-14 12:16
> > I figured as much when looking at the codebase. I only stepped through the `SyncSubmitBlock` impl and there I saw that the created tipset doesn't get a CID assigned to it at that point in time. After that I didn't know where to follow the propagation of the block to see if it gets recorded anywhere using `GetChainBlock`, because I couldn't find its CID if it did.
> 
> That is helpful, let me check..

@alt-ivan in fact `key` is lazily initialized on `fn key()` call.
https://github.com/ChainSafe/forest/blob/4a6ad5c8f4c90ed0dcf13f3069540545fad0a8f4/src/blocks/tipset.rs#L301-L304

So you can basically check the CIDs of `headers` to see which ones to monitor. 

For further debugging:

1. Here's where tipset channel is being consumed: https://github.com/ChainSafe/forest/blob/32ae416f8dbd34a2e0eadf0ffbbeb9846e41e380/src/chain_sync/tipset_syncer.rs#L348
2. Here's where the rest of the logic happens: https://github.com/ChainSafe/forest/blob/32ae416f8dbd34a2e0eadf0ffbbeb9846e41e380/src/chain_sync/tipset_syncer.rs#L375-L573

**Comment by alt-ivan** [comment] 2024-05-14 16:34
@ruseinov 

I tried to adapt lotus-miner so I can give you easy steps to reproduce (to stop at `MinerCreateBlock` so you can feed the output of that into `SyncSubmitBlock`) but I ran into so many speedbumps that I gave up for now.

Some new interesting info:

> So you can basically check the CIDs of headers to see which ones to monitor.

When I connect Forest/Lotus and execute `SyncSubmitBlock` on Forest, it propagates that block to Lotus and Lotus now has the correct chain head with the latest tipset. Forest also receives this block, seemingly back from Lotus via gossip, because I can query it via `GetChainBlock` and see it. However, Forest's `ChainHead` still points to the previous epoch tipset.

When I don't connect Forest/Lotus and execute `SyncSubmitBlock` on Forest, then that block doesn't get stored and I cannot query it via `GetChainBlock`


> Here's where tipset channel is being consumed: 

I added tracing into these locations and nothing happens. Doing some more eye-level examination I saw this:
```rust
    fn follow(&self, tipset_opt: Option<FullTipset>) -> ChainMuxerFuture<(), ChainMuxerError> {
        // Instantiate a TipsetProcessor
  ```

But in devnet it seems that Forest never enters follow mode https://github.com/ChainSafe/forest/issues/3089
From what I saw, `tipset_receiver` only gets consumed here via `TipsetProcessor`? I might be wrong though.

This may also explain other sync issues with Lotus in devnet i.e. Forest often doesn't sync fully with Lotus with similar "symptoms" (ChainHead returns earlier tipset but later one exists in store)

**Comment by ruseinov** [comment] 2024-05-14 17:25
@alt-ivan Thanks a lot for looking into this, no it starts to make a lot of sense!

> When I don't connect Forest/Lotus and execute `SyncSubmitBlock` on Forest, then that block doesn't get stored and I cannot query it via `GetChainBlock`
> 
> >

That's probably due to the fact that the actual network send works, but the `TipsetProcessor` part does not work.




> But in devnet it seems that Forest never enters follow mode #3089

You are correct, it seems it never does. Good spot! And logically you can submit a block if the node is never "in sync".  I guess we'll have to deal with it to fix this.

**Comment by ruseinov** [comment] 2024-05-15 13:49
@alt-ivan Can you please try going through the process using this commit: https://github.com/ChainSafe/forest/pull/4328 ?
It's going to be merged to master automatically in a little bit. This should fix the `follow` issue.

**Comment by alt-ivan** [comment] 2024-05-15 14:03
@ruseinov 
I will be testing shortly and reporting back here. Thanks!

**Closed** 2024-08-02 15:48 UTC
Labels: Type: Bug, Priority: 2 - High, Type: Feature
